name: CI/CD

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  # build-test:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up JDK 21
  #     uses: actions/setup-java@v4
  #     with:
  #         java-version: '21'
  #         distribution: 'temurin'
          
  #   - name: Build and Test Backend
  #     working-directory: ./
  #     run: |
  #         ./mvnw clean install
  #         ./mvnw test
  build-push-docker:
    runs-on: ubuntu-latest
    # needs: build-test

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag krystine825/expense_tracker:latest

    - name: Login to Docker Hub
      run: echo "dckr_pat_u3CM_bQu_Qp4yZbJg8jcD0qWYSM" | docker login -u krystine825 --password-stdin


    - name: Push to the Docker Hub
      run: docker push krystine825/expense_tracker:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build-push-docker

    steps:
    - name: Install ArgoCD CLI
      run: |
        VERSION=$(curl -s https://api.github.com/repos/argoproj/argo-cd/releases/latest | grep tag_name | cut -d '"' -f 4)
        curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/download/${VERSION}/argocd-linux-amd64
        chmod +x argocd
        sudo mv argocd /usr/local/bin/

    - name: Login to ArgoCD
      run: |
        argocd login 35.240.211.197 --username admin --password 2RGYwoGp4B4naQE5 --insecure

    - name: Sync ArgoCD Application
      run: |
        argocd app sync web --force --prune
